language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
  - python: "3.5"
    env: PYTHONASYNCIODEBUG=x
  - python: "3.6"
    env: PYTHONASYNCIODEBUG=x
  - python: "3.7"
    env: PYTHONASYNCIODEBUG=x
  - python: "3.8"
    env: PYTHONASYNCIODEBUG=x

before_install:
  - pip install poetry more-itertools
install:
  - poetry install
script: poetry run make check
after_success: coveralls
notifications:
  email: false
