name: CI

on:
  push:
  pull_request:

jobs:

  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, pypy3]
        # XML coverage reporting is broken for this particular configuration
        exclude:
          - os: windows-latest
            python-version: pypy3
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: python setup.py test --addopts "--cov-report xml"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON

  Release:
    runs-on: ubuntu-latest
    needs: [Quality, Tests]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build source distribution
        run: python setup.py sdist
      - name: Publish source package on PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
